language: python
sudo: false
python:
  - "3.8"
  - "3.9"
install: pip install tox-travis pycodestyle coverage
script: tox
before_script: pycodestyle --ignore=E501,E225,W503 password_policies
after_success: coveralls
